### ISSUE TITLE
Bug if you use html minifier

### ISSUE THREAD

**Issue by geckokiev** [cofess/hexo-theme-pure#11]
Bug if you use html_minifier or hexo-neat...
`</head></html><body class="main-center" itemscope itemtype="http://schema.org/WebPage"><header class`
You can see here: **http://blog.cofess.com** (source code)
></head>**</html>**<body class="main-center" itemscope itemtype="http://schema.org/WebPage"><header class

how to fix?

**Comment by cofess** [comment]
这一段有什么问题？

**Comment by dan1313** [comment]
</html><body class="main-center" itemscope itemtype="http://schema.org/WebPage">

**Comment by dan1313** [comment]
Simple recursive replacement of text
`</html> replace on ""`
&
`</body> replace on </body></html>`

**Comment by cofess** [comment]
Theme updated. It fixed!
