### ISSUE TITLE
开启了toc但还是不显示文章目录

### ISSUE THREAD

**Issue by simple-zhou** [cofess/hexo-theme-pure#125]
可以显示文章目录吗，看着很不方便

**Comment by ziiyan** [comment]
https://github.com/cofess/hexo-theme-pure/issues/33#issuecomment-529211389
https://github.com/cofess/hexo-theme-pure/issues/33#issuecomment-529215412
这两个都改掉就可以了

**Comment by simple-zhou** [comment]
> [#33 (comment)](https://github.com/cofess/hexo-theme-pure/issues/33#issuecomment-529211389)
> [#33 (comment)](https://github.com/cofess/hexo-theme-pure/issues/33#issuecomment-529215412)
> 这两个都改掉就可以了
可以了，感谢！！！

**Comment by simple-zhou** [comment]
![image](https://user-images.githubusercontent.com/43675156/88802376-91a97180-d1dd-11ea-95b5-8ff4ef749b9b.png)

**Comment by simple-zhou** [comment]
1. 把layout/_partial/post/nav.ejs，layout/_partial/sidebar-toc.ejs里的&& post.toc删掉
2. sidebar-toc.ejs把collapse这个样式去掉可以了，这个样式写了一个display:none!important; 不知道为什么要隐藏
Mark一下
