### ISSUE TITLE
自定义菜单页面

### ISSUE THREAD

**Issue by Ik0nw** [cofess/hexo-theme-pure#129]
想自定义一个 `Todo` 菜单选项。
修改了config.yml里的menu

![image](https://user-images.githubusercontent.com/48197340/93706028-fc7b8700-fb54-11ea-9323-47f4078afb38.png)

为什么显示的是menu.Todo？

**Comment by hwame** [comment]
我把「书单」魔改成了「留言簿」，最近又想改成相册，但是不知道怎么弄、、、
你改的时候不能只改`config.yml`，相应的位置都要改，**仅供参考**。。
- `./themes/pure/_source/new_page`，页面文件夹
- `./themes/pure/languages/zh-CN.yml`
- `./themes/pure/layout/new_page.ejs`，这里也可以直接用已有的样式，保持对应
- `./themes/pure/layout/_partial/archive-new_page.ejs`
不知道还有没有，欢迎交流，[我在这里](https://hwame.github.io/)

**Comment by Ik0nw** [comment]
> 我把「书单」魔改成了「留言簿」，最近又想改成相册，但是不知道怎么弄、、、
> 你改的时候不能只改`config.yml`，相应的位置都要改，**仅供参考**。。
> 
> * `./themes/pure/_source/new_page`，页面文件夹
> * `./themes/pure/languages/zh-CN.yml`
> * `./themes/pure/layout/new_page.ejs`，这里也可以直接用已有的样式，保持对应
> * `./themes/pure/layout/_partial/archive-new_page.ejs`
>   不知道还有没有，欢迎交流，[我在这里](https://hwame.github.io/)

找到问题了，是我 语言文件里 没有添加。 感谢！
