### ISSUE TITLE
Does not work Toc menu

### ISSUE THREAD

**Issue by dan1313** [cofess/hexo-theme-pure#13]
Does not work **Toc** menu

> config:
>   layout: main-center # 布局方式 main-left main-center main-right
>   **toc: true** 

Most likely an error here:
_partial/article.ejs & sidebar-toc.ejs
`<% if (!index && theme.config.toc && post.toc) { %>`
If you remove the check **post.toc,** then everything works
`<% if (!index && theme.config.toc) { %>`
or
`<% if (theme.config.toc) { %>`

**Comment by cofess** [comment]
It works! You can open it in the article.
> title: Hexo博客常用插件及用法
toc: true
permalink: comon-plugins-and-usage-of-hexo-blog
date: 2017-08-16 13:16:27

**Comment by dan1313** [comment]
tnx!
