### ISSUE TITLE
咋都 页面 Error

### ISSUE THREAD

**Issue by zerocc2014** [cofess/hexo-theme-pure#15]
![image](https://user-images.githubusercontent.com/16301538/32416924-ea91a7ba-c216-11e7-9420-8a7f13ca4377.png)

INFO  Start processing
INFO  Files loaded in 451 ms
WARN  Partial common/thumbnail.ejs does not exist. (in _widget/recent_posts.ejs)
WARN  Partial common/thumbnail.ejs does not exist. (in _widget/recent_posts.ejs)
WARN  Partial common/thumbnail.ejs does not exist. (in _widget/recent_posts.ejs)
WARN  Partial common/thumbnail.ejs does not exist. (in _widget/recent_posts.ejs)
WARN  Partial common/thumbnail.ejs does not exist. (in _widget/recent_posts.ejs)
INFO  0 files generated in 566 ms

**Comment by dan1313** [comment]
Создай папку /source/categories, в ней нужно создать файл index.md с таким содержанием: 
```
title: Categories
layout: categories
comments: false
---
```

**Comment by zerocc2014** [comment]
![image](https://user-images.githubusercontent.com/16301538/32439721-8f9824ca-c2b5-11e7-9ed6-a5aba44e5b90.png)
![image](https://user-images.githubusercontent.com/16301538/32439734-a070761c-c2b5-11e7-964d-10a3bc0d9e00.png)

**Comment by geckokiev** [comment]
Странно, файла **thumbnail.ejs** [не должно быть ](https://github.com/cofess/hexo-theme-pure/tree/master/layout/_common)
Выполните комманду: **hexo clean**

**Comment by zerocc2014** [comment]
I can not understand  ，can you writer by English

**Comment by zerocc2014** [comment]
_config.yml：
# config
config:
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: false # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More
  fancybox: false

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true

And
recent_posts.ejs:
<% if (site.posts.length){ %>
  <div class="widget">
    <h3 class="widget-title"><%= __('widget.recent_posts') %></h3>
    <div class="widget-body">
      <ul class="recent-post-list list-unstyled <%= (theme.config.thumbnail?'':'no-thumbnail') %>">
        <% site.posts.sort('date', -1).limit(5).each(function(post){ %>
          <li>
            <% if(theme.config.thumbnail == true) { %>
            <div class="item-thumbnail">
              <%- partial('common/thumbnail.ejs', {post: post}) %>
            </div>
            <% } %>
            <div class="item-inner">
              <p class="item-category">
                <%- list_categories(post.categories, {show_count: false, depth:2, class: 'category', style: 'none', separator: '<i class="fa fa-angle-right"></i>'}) %>
              </p>
              <p class="item-title">
                <a href="<%- url_for((post.link?post.link:post.path)) %>" class="title"><%= post.title || '(no title)' %></a>
              </p>
              <p class="item-date">
                <time datetime="<%= date_xml(post.date) %>" itemprop="datePublished"><%= date(post.date) %></time>
              </p>
            </div>
          </li>
          <% }) %>
      </ul>
    </div>
  </div>
  <% } %>


but still Error

**Comment by GeckoKiev** [comment]
Reload [theme files](https://github.com/cofess/hexo-theme-pure) & enter command: 
```
cd /path/to/hexo.site  
hexo clean
```

**Comment by cofess** [comment]
Theme updated! Fixed some bugs.
