### ISSUE TITLE
页面样式完全丢失

### ISSUE THREAD

**Issue by DoneSpeak** [cofess/hexo-theme-pure#18]
![image](https://user-images.githubusercontent.com/16522248/33234024-88f7684c-d25a-11e7-91a5-423bc51eec94.png)

我还没有进行博客优化，就完成了基本的配置。

**Comment by DoneSpeak** [comment]
原来下面的几步需要在blog的根目录安装的，新手完全不知道这个，终于解决一个问题了，继续配置。
hexo-generator-feed
npm install hexo-generator-feed --save

hexo-generator-sitemap
npm install hexo-generator-sitemap --save

hexo-generator-baidu-sitemap
npm install hexo-generator-baidu-sitemap --save

**Comment by cofess** [comment]
新手建议先看一下Hexo文档
