### ISSUE TITLE
如何配置：‘分类’，‘标签’，‘项目’，‘书单’，‘友链’，‘关于’ 页面呢？

### ISSUE THREAD

**Issue by StoneMa** [cofess/hexo-theme-pure#29]
按照您的文档上的方法配置，生成的主题只有‘首页’，和 ‘归档’ 是正常显示的，下面的title点击后都跳转到另一个页面，各个栏目下的index.md文件中的layout也进行了设置，但是不起作用。
![image](https://user-images.githubusercontent.com/6917909/35723120-1b14c2d8-0834-11e8-8a8b-af17771c1484.png)

**点击分类后：**
![image](https://user-images.githubusercontent.com/6917909/35723146-2cae1ed6-0834-11e8-932a-460e0f740f65.png)

**其他按钮也有相同问题：**
![image](https://user-images.githubusercontent.com/6917909/35723171-4c64548e-0834-11e8-9cb0-5b52dc317d2c.png)

**Comment by cofess** [comment]
有报错吗？我这一直是正常的

**Comment by StoneMa** [comment]
没有报错，我想知道，您这边配置完了，就显示正常了吗？‘分类’，‘标签’，‘项目’，‘书单’，‘友链’，‘关于’ 这些title点进去，就直接可以在右侧显示相关内容了么？我看_config.yml相关的title已经在里面了，然后按照您博客中的方法，把_source 中相关的文件夹拷贝到source文件夹内，然后执行了hexo g , hexo s 全程没有报错信息。但是访问本机下的页面的时就出现上面的问题了。

**Comment by StoneMa** [comment]
我又重新安装了一遍，安装完毕后点击左侧link是这样的：

![1](https://user-images.githubusercontent.com/6917909/35765728-feed5756-0904-11e8-8b13-c5ee541e7c27.jpg)

**点击红框中的任意一个link 都会调到这样的页面：**

![image](https://user-images.githubusercontent.com/6917909/35765732-1b0c7084-0905-11e8-9d4a-759df8dedcb5.png)

这是按照您git上的方法配置的。

**Comment by StoneMa** [comment]
好了，弄好了，我source下的文件目录设置有问题。
