### ISSUE TITLE
归档不显示

### ISSUE THREAD

**Issue by SwimmingFish6** [cofess/hexo-theme-pure#39]
打开归档之后就会404报错，查看了一下public目录下不会生成archive目录，是因为脚本缺失吗

**Comment by cofess** [comment]
pure/_source/路径下，复制categories整个文件夹到博客source目录

**Comment by cofess** [comment]
生成的时候有报错吗？

**Comment by SwimmingFish6** [comment]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/24370193/39160736-d98e87b8-4721-11e8-9c29-f2b3315ba97a.png">
build完的截图是这样的，并没有报错，似乎就是没有生成archive对应的文件夹以及其index.html，
<img width="665" alt="image" src="https://user-images.githubusercontent.com/24370193/39160756-00a8a914-4722-11e8-8419-0431e66d0c7b.png">
source里面这些文档应该也都复制进去了

**Comment by cofess** [comment]
我用公司电脑试了一遍，正常，不知道你这个什么原因，你换其他主题看一下能不能生成archive

**Comment by SwimmingFish6** [comment]
重新建立一遍project之后解决了，分析应该是之前在theme内部不小心安装了一些npm包的缘故
