### ISSUE TITLE
该主题下的markdwon文件插入公式错误

### ISSUE THREAD

**Issue by STHSF** [cofess/hexo-theme-pure#4]
我在使用该主题后在markdown下编辑公式，但是提交后始终是显示不出来，我也使用了一些方法来处理，比如说替换marked.js，安装pandoc之类的，但是都没有效果。请问如何解决。

**Comment by cofess** [comment]
什么样的公式？换一个markdown渲染引擎试一下，Hexo默认使用"hexo-renderer-marked"引擎渲染网页，好像会强制转换一些特殊字符

**Comment by STHSF** [comment]
就是正常的latex语法的公式。我也将原来的渲染引擎换成了“hexo-renderer-kramed”，也修改了一些转译字符，比如escape: /^\\([`*\[\]()#$+\-.!_>])/和 em: /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/。这种方法没有效果。然后我又跟换为“hexo-renderer-pandoc”引擎，但也还是没有效果。所以我问下你在博客里插入公式的时候有没有遇到这样的情况。

**Comment by cofess** [comment]
更新了一下dev分支，已经支持数学公式，具体配置看[readme](https://github.com/cofess/hexo-theme-pure/tree/dev#数学公式)

**Comment by STHSF** [comment]
我按照上面的步骤做了一下，为什么我没有生成mathjax.ejs文件，还是这个文件需要自己手动添加？

**Comment by cofess** [comment]
主题已经支持数学公式，用hexo-renderer-markdown-it-plus引擎替换默认的渲染引擎hexo-renderer-marked即可

**Comment by STHSF** [comment]
嗯 对的 我已经替换了，但是还是不行，所以不知道问题出在哪儿？我是需要重新将主题pull下来么

**Comment by cofess** [comment]
本地主题要更新一下

**Comment by STHSF** [comment]
OK,懂了,谢谢......
