### ISSUE TITLE
Latex公式显示问题

### ISSUE THREAD

**Issue by const7** [cofess/hexo-theme-pure#45]
本地显示是这样
![image](https://user-images.githubusercontent.com/19154386/40664659-022eeb58-638e-11e8-8286-7a28231ee183.png)
上传之后直接无法显示公式
![image](https://user-images.githubusercontent.com/19154386/40664838-665603b4-638e-11e8-8716-ff5003134465.png)
另外发现你的博客上的两篇文章，第一篇也存在显示漂移的问题，http://blog.cofess.com/2017/09/06/how-to-use-mathjax-to-render-latex-mathematical-formula-in-hexo.html
这一篇是正常的，http://blog.cofess.com/2017/09/06/how-to-use-mathjax-to-render-latex-mathematical-formulas-in-hexo.html
PS：win10， chrome浏览器

**Comment by zer01ike** [comment]
解决了，修改一下pure/layout/_common/plugin.ejs中的mathjax选项里面的cdn链接版本号即可。
```
<% if (page.mathjax) { %>
        <link href="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.css" rel="stylesheet">
<% } %>

改为：
<% if (page.mathjax) { %>
        <link href="https://cdn.bootcss.com/KaTeX/0.8.3/katex.min.css" rel="stylesheet">
<% } %>
```
<img width="370" alt="screen shot 2018-08-27 at 09 45 01" src="https://user-images.githubusercontent.com/31384713/44636358-f77f9400-a9dd-11e8-98af-c3e4704d9784.png">
