### ISSUE TITLE
关于统计的问题

### ISSUE THREAD

**Issue by zhaokuankuan** [cofess/hexo-theme-pure#56]
同理，有人已经提了一个issues了，同样的错误，请问这个请求400的问题是咋样出现的，我也看了官网的文档，一模一样呀，给提点个处理的思路。谢谢

**Comment by zhaokuankuan** [comment]
这个问题我已经解决了，希望博主能够更新上去！不设置referrer得话请求会 400 ，需要加上如下得语句，我加在了footer.ejs得最上面。

<meta name="referrer" content="no-referrer-when-downgrade" />

**Comment by inkss** [comment]
统计功能没用过直接关闭了，不过如果只是涉及 `referrer` 的话，这个我碰到过。

所有链接没有带 referrer 是因为网页的头部里写成了这个样子：

```html
<meta name=referrer content=never>
```

如果是为了恢复让请求头带来源信息的话只需要把 never 换成 `origin` 。

链接如下：[3.2 恢复 referrer](https://inkss.cn/2018/09/15/hexo-blog-build/#3-2-%E6%81%A2%E5%A4%8D-referrer)
