### ISSUE TITLE
访问根目录下.json文件

### ISSUE THREAD

**Issue by liuzhihangs** [cofess/hexo-theme-pure#66]
请教一个问题:
![image](https://user-images.githubusercontent.com/26057042/47278951-86d0ae80-d5ff-11e8-9e88-46462a4e239f.png)
项目根目录下存在很多文件, 大部分都可以通过域名加文件名的方式访问
其中 posts.json tags.json categories.json 发现直接访问不了, 是需要修改哪边的前端代码么?
@cofess

**Comment by cofess** [comment]
`content.json`是可以访问的，可能github限制了吧，可以试下`robots.txt`，找到一个插件：https://www.npmjs.com/package/hexo-generator-robotstxt

**Comment by liuzhihangs** [comment]
是可以访问  content.json 但是访问  posts.json tags.json categories.json 会自动跳转到404 页面
刚才试着添加了 robots.txt 访问后依然会跳转到 404 页面
https://liuzhihang.com/robots.txt

**Comment by liuzhihangs** [comment]
@cofess 
听说是github 挂了, 刚才我测试新提交一篇blog 发现不能正常显示. 旧的现在不受影响.
应该是这个问题, 所以google 也找不到自己的 robots.txt, 以及新提交的内容都会跳转到404

具体等正常后再看. 打扰啦, 谢谢

**Comment by liuzhihangs** [comment]
已经正常了, 感谢帮忙查看, 可以关闭了.
