### ISSUE TITLE
图标不能正常加载

### ISSUE THREAD

**Issue by ShengdongYan** [cofess/hexo-theme-pure#79]
为什么我网页上的图标一直不显示呢，尝试了很多办法还是不行，我打开其他人的页面，他们的Favicon都是正常的，但是生成的indec.html里的 icon 那都是乱码，却显示正常。 我的不是乱码反而不显示。

**Comment by ShengdongYan** [comment]
我可能没太说清除，我说的图标是favicon, 在config里的site那边设置的那个图标。我图片放在source下面，名字是favicon.png。  我的配置是默认的 favicon: /favicon.png.  这样我的图标是不正常显示的。 我试着把图标位置换到了images文件夹下，配置改成了favicon: images/favicon.png. 这样的话首页图标正常了，但是其他页的图标依然不能显示，能解答一下吗？

**Comment by ShengdongYan** [comment]
我看其他人生成后的html里' <link rel="icon" href="data/乱码" type="image/x-icon">'  里边是乱码，却正常显示了，我的是 <link rel="icon" href="images/favicon.png" type="image/x-icon">，却不能正常显示。

**Comment by cofess** [comment]
@ShengdongYan 看了一下你的博客，正常显示呀

**Comment by ShengdongYan** [comment]
谢谢，我又修改了一下， 加了/images/favicon.png, 写成了网络绝对路径就解决了，开心。
