### ISSUE TITLE
您好，最近链接图片展示 好像显示不出来

### ISSUE THREAD

**Issue by LiuChuang0059** [cofess/hexo-theme-pure#83]
您好，最近链接图片展示 有些页面好像显示不出来

**Comment by LiuChuang0059** [comment]
好像是使用 新浪图床的链接在博客都无法显示

**Comment by AprilYoLies** [comment]
你可以看看文章的静态html文件，生成的图片链接是否是正确的。。

**Comment by shanlanCoding** [comment]
> 好像是使用 新浪图床的链接在博客都无法显示

---------
新浪开启了防盗链，图片不显示很正常。

**Comment by shanlanCoding** [comment]
所以如果问题解决了的话，可以关闭这个issues
